receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:

exporters:
  debug:
    verbosity: detailed
    sampling_initial: 5
    sampling_thereafter: 200

  otlp:
    endpoint: "jaeger:4317"
    tls:
      insecure: true
  prometheus:
    endpoint: "0.0.0.0:9464"
  logging:
    loglevel: debug

connectors: # TODO DROP IT 
  spanmetrics:
    exemplars:
      enabled: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [spanmetrics, otlp]
    metrics:
      receivers: [spanmetrics, otlp]
      processors: [batch]
      exporters: [logging, prometheus]
    logs:
      receivers: [otlp]
      exporters: [debug]

# I need a docker-compose.yml that will have  jaegertracing/all-in-one ,  prom/prometheus and otel/opentelemetry-collecto
# where opentelemetry-collecto collect traces and send it to jaeger, metrics to prometheus and jaeger read metrics from prometheus
# also I will need config files for all of them
# thank you
